evm-network-id: 100
price-multiplier: 1
issue-creator-multiplier: 2
private-key-encrypted: "YU-tFJFczN3JPVoJu0pQKSbWoeiCFPjKiTXMoFnJxDDxUNX-BBXc6ZHkcQcHVjdOd6ZcEnU1o2jU3F-i05mGJPmhF2rhQYXkNlxu5U5fZMMcgxJ9INhAmktzRBUxWncg4L1HOalZIoQ7gm3nk1a84g"
time-labels:
  - name: "Time: <1 Hour"
  - name: "Time: <2 Hours"
  - name: "Time: <4 Hours"
  - name: "Time: <1 Day"
  - name: "Time: <1 Week"
priority-labels:
  - name: "Priority: 0 (Normal)"
  - name: "Priority: 1 (Medium)"
  - name: "Priority: 2 (High)"
  - name: "Priority: 3 (Urgent)"
  - name: "Priority: 4 (Emergency)"
default-labels:
  - "Time: <1 Hour"
  - "Priority: 0 (Normal)"
command-settings:
  - name: start
    enabled: true
  - name: stop
    enabled: true
  - name: wallet
    enabled: true
  - name: payout
    enabled: true
  - name: multiplier
    enabled: true
  - name: query
    enabled: true
  - name: allow
    enabled: true
  - name: autopay
    enabled: true
payment-permit-max-price: 1000
comment-incentives: true
disable-analytics: false
max-concurrent-assigns: 2
promotion-comment: "\n<h6>If you enjoy the DevPool experience, please follow <a href='https://github.com/ubiquity'>Ubiquity on GitHub</a> and star <a href='https://github.com/ubiquity/devpool-directory'>this repo</a> to show your support. It helps a lot!</h6>"
register-wallet-with-verification: false
assistive-pricing: true
incentives:
  comment:
    elements:
      code: 5
      img: 5
      h1: 1
      li: 0.5
      a: 0.5
      blockquote: 0
    totals:
      word: abcde

